# Generated by Django 4.2.27 on 2025-12-09 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('table', 'Data Table Preview'), ('linear_regression', 'Linear Regression'), ('clustering', 'Clustering (KMeans)'), ('distribution', 'Distribution Plot'), ('statistical_summary', 'Statistical Summary'), ('eda_report', 'Full EDA Report'), ('correlation', 'Correlation Matrix'), ('scatter', 'Scatter Plot'), ('histogram', 'Histogram'), ('boxplot', 'Box Plot')], max_length=50)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('result_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='dataanalysis.uploadedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
